# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a49df6c7ce5ca7a5af58911c9188183b5d258512911f2c5a02113b60ea945df68c9610a825d8d8c00b105b090ed4a1770ad14a5662acd2989a3c0c2a8a2d3a9f

test:
  secret_key_base: a259f04abac761990435364a873f9c2fc6cfd062fae186a61f2db59fdcbddaab8d6065d995775d42092852dc8ba98c3137b67add3612742c6910d5b317da0c79

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
